name: main
on:
  push:
    branches: [master, wasm]
  pull_request:
jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo npm install -g jshint; make jshint
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: cache-rustup
      with:
        path: ~/.cache/rustup/
        key: ${{ runner.os }}-rustup
    - name: rustup
      run: |
        rustup toolchain install stable
        rustup target add wasm32-unknown-unknown
        rustup component add rustfmt

    - name: apt install
      run: sudo apt update -qq; sudo apt install nasm gdb qemu-system-x86 libc6-dev-i386
    - name: make all
      run: make all

    - uses: actions/cache@v2
      id: cache-images
      with:
        path: images/
        key: ${{ runner.os }}-images-v2
    - name: get images
      if: steps.cache-images.outputs.cache-hit != 'true'
      run: wget -nv -P images/ https://k.copy.sh/{linux.iso,linux3.iso,linux4.iso,buildroot-bzimage.bin,TinyCore-11.0.iso,oberon.img,msdos.img,openbsd-floppy.img,kolibri.img,windows101.img,os8.img,freedos722.img,mobius-fd-release5.img}
